PDF_INPUTS := title-and-toc.pdf {% for file in config.includes %}{{file.path}} {%endfor%}
PADDING := {%for n in range(context.filler_page_count)%}{{context.filler_page}} {%endfor%}

all: {{context.output_base}}.pdf

combined.pdf: $(PDF_INPUTS) {{context.blank_page}}
	pdfunite $(PDF_INPUTS) $(PADDING) combined.pdf

title-and-toc.pdf: title-and-toc.tex
	pdflatex title-and-toc.tex

combined.ps: combined.pdf
	pdftops combined.pdf

numbered.ps: combined.ps {{ context.number_script }}
	awk -f '{{ context.number_script }}' combined.ps > numbered.ps

book.ps: numbered.ps
	psbook numbered.ps > book.ps

{{context.output_base}}.ps: book.ps
	psnup -2 --transpose book.ps {{context.output_base}}.ps

{{context.output_file}}: {{context.output_base}}.ps
	ps2pdf {{context.output_base}}.ps

clean:
	rm -f {{context.output_base}}.ps {{context.output_file}} numbered.ps combined.ps book.ps
